export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const CLEAR_AUTH_STATE = "CLEAR_AUTH_STATE";
export const LOGOUT_USER = "LOGOUT_USER";

export const GET_CONTACTS_REQUEST = "GET_CONTACTS_REQUEST";
export const GET_CONTACTS_SUCCESS = "GET_CONTACTS_SUCCESS";
export const GET_CONTACTS_FAIL = "GET_CONTACTS_FAIL";

export const CREATE_CONTACT_REQUEST = "CREATE_CONTACT_REQUEST";
export const CREATE_CONTACT_SUCCESS = "CREATE_CONTACT_SUCCESS";
export const CREATE_CONTACT_FAIL = "CREATE_CONTACT_FAIL";

export const DELETE_CONTACT_REQUEST = "DELETE_CONTACT_REQUEST";
export const DELETE_CONTACT_SUCCESS = "DELETE_CONTACT_SUCCESS";
export const DELETE_CONTACT_FAIL = "DELETE_CONTACT_FAIL";

export const EDIT_CONTACT_REQUEST = "EDIT_CONTACT_REQUEST";
export const EDIT_CONTACT_SUCCESS = "EDIT_CONTACT_SUCCESS";
export const EDIT_CONTACT_FAIL = "EDIT_CONTACT_FAIL";

// CARRIER

export const CREATE_CARRIER_REQUEST = "CREATE_CARRIER_REQUEST";
export const CREATE_CARRIER_SUCCESS = "CREATE_CARRIER_SUCCESS";
export const CREATE_CARRIER_FAIL = "CREATE_CARRIER_FAIL";

export const EDIT_CARRIER_REQUEST = "EDIT_CARRIER_REQUEST";
export const EDIT_CARRIER_SUCCESS = "EDIT_CARRIER_SUCCESS";
export const EDIT_CARRIER_FAIL = "EDIT_CARRIER_FAIL";

export const GET_CARRIERS_REQUEST = "GET_CARRIERS_REQUEST";
export const GET_CARRIERS_SUCCESS = "GET_CARRIERS_SUCCESS";
export const GET_CARRIERS_FAIL = "GET_CARRIERS_FAIL";

export const GET_CARRIER_BY_CRITERIA_REQUEST =
  "GET_CARRIER_BY_CRITERIA_REQUEST";
export const GET_CARRIER_BY_CRITERIA_SUCCESS =
  "GET_CARRIER_BY_CRITERIA_SUCCESS";
export const GET_CARRIER_BY_CRITERIA_FAIL = "GET_CARRIER_BY_CRITERIA_FAIL";

export const DELETE_CARRIER_REQUEST = "DELETE_CARRIER_REQUEST";
export const DELETE_CARRIER_SUCCESS = "DELETE_CARRIER_SUCCESS";
export const DELETE_CARRIER_FAIL = "DELETE_CARRIER_FAIL";

//VEHICLE

export const CREATE_VEHICLE_REQUEST = "CREATE_VEHICLE_REQUEST";
export const CREATE_VEHICLE_SUCCESS = "CREATE_VEHICLE_SUCCESS";
export const CREATE_VEHICLE_FAIL = "CREATE_VEHICLE_FAIL";

export const EDIT_VEHICLE_REQUEST = "EDIT_VEHICLE_REQUEST";
export const EDIT_VEHICLE_SUCCESS = "EDIT_VEHICLE_SUCCESS";
export const EDIT_VEHICLE_FAIL = "EDIT_VEHICLE_FAIL";

export const GET_VEHICLES_REQUEST = "GET_VEHICLES_REQUEST";
export const GET_VEHICLES_SUCCESS = "GET_VEHICLES_SUCCESS";
export const GET_VEHICLES_FAIL = "GET_VEHICLES_FAIL";

export const GET_VEHICLE_BY_CRITERIA_REQUEST =
  "GET_VEHICLE_BY_CRITERIA_REQUEST";
export const GET_VEHICLE_BY_CRITERIA_SUCCESS =
  "GET_VEHICLE_BY_CRITERIA_SUCCESS";
export const GET_VEHICLE_BY_CRITERIA_FAIL = "GET_VEHICLE_BY_CRITERIA_FAIL";

export const DELETE_VEHICLE_REQUEST = "DELETE_VEHICLE_REQUEST";
export const DELETE_VEHICLE_SUCCESS = "DELETE_VEHICLE_SUCCESS";
export const DELETE_VEHICLE_FAIL = "DELETE_VEHICLE_FAIL";

//DRIVER

export const CREATE_DRIVER_REQUEST = "CREATE_DRIVER_REQUEST";
export const CREATE_DRIVER_SUCCESS = "CREATE_DRIVER_SUCCESS";
export const CREATE_DRIVER_FAIL = "CREATE_DRIVER_FAIL";

export const EDIT_DRIVER_REQUEST = "EDIT_DRIVER_REQUEST";
export const EDIT_DRIVER_SUCCESS = "EDIT_DRIVER_SUCCESS";
export const EDIT_DRIVER_FAIL = "EDIT_DRIVER_FAIL";

export const GET_DRIVERS_REQUEST = "GET_DRIVERS_REQUEST";
export const GET_DRIVERS_SUCCESS = "GET_DRIVERS_SUCCESS";
export const GET_DRIVERS_FAIL = "GET_DRIVERS_FAIL";

export const GET_DRIVER_REQUEST = "GET_DRIVER_REQUEST";
export const GET_DRIVER_SUCCESS = "GET_DRIVER_SUCCESS";
export const GET_DRIVER_FAIL = "GET_DRIVER_FAIL";

export const DELETE_DRIVER_REQUEST = "DELETE_DRIVER_REQUEST";
export const DELETE_DRIVER_SUCCESS = "DELETE_DRIVER_SUCCESS";
export const DELETE_DRIVER_FAIL = "DELETE_DRIVER_FAIL";

//LOAD

export const CREATE_LOAD_REQUEST = "CREATE_LOAD_REQUEST";
export const CREATE_LOAD_SUCCESS = "CREATE_LOAD_SUCCESS";
export const CREATE_LOAD_FAIL = "CREATE_LOAD_FAIL";

export const EDIT_LOAD_REQUEST = "EDIT_LOAD_REQUEST";
export const EDIT_LOAD_SUCCESS = "EDIT_LOAD_SUCCESS";
export const EDIT_LOAD_FAIL = "EDIT_LOAD_FAIL";

export const GET_LOADS_REQUEST = "GET_LOADS_REQUEST";
export const GET_LOADS_SUCCESS = "GET_LOADS_SUCCESS";
export const GET_LOADS_FAIL = "GET_LOADS_FAIL";

export const GET_LOAD_BY_CRITERIA_REQUEST = "GET_LOAD_BY_CRITERIA_REQUEST";
export const GET_LOAD_BY_CRITERIA_SUCCESS = "GET_LOAD_BY_CRITERIA_SUCCESS";
export const GET_LOAD_BY_CRITERIA_FAIL = "GET_LOAD_BY_CRITERIA_FAIL";

export const DELETE_LOAD_REQUEST = "DELETE_LOAD_REQUEST";
export const DELETE_LOAD_SUCCESS = "DELETE_LOAD_SUCCESS";
export const DELETE_LOAD_FAIL = "DELETE_LOAD_FAIL";

// SHIPMENT

export const CREATE_SHIPMENT_REQUEST = "CREATE_SHIPMENT_REQUEST";
export const CREATE_SHIPMENT_SUCCESS = "CREATE_SHIPMENT_SUCCESS";
export const CREATE_SHIPMENT_FAIL = "CREATE_SHIPMENT_FAIL";

export const EDIT_SHIPMENT_REQUEST = "EDIT_SHIPMENT_REQUEST";
export const EDIT_SHIPMENT_SUCCESS = "EDIT_SHIPMENT_SUCCESS";
export const EDIT_SHIPMENT_FAIL = "EDIT_SHIPMENT_FAIL";

export const GET_SHIPMENTS_REQUEST = "GET_SHIPMENTS_REQUEST";
export const GET_SHIPMENTS_SUCCESS = "GET_SHIPMENTS_SUCCESS";
export const GET_SHIPMENTS_FAIL = "GET_SHIPMENTS_FAIL";

export const GET_INTEREST_REQUEST = "GET_INTEREST_REQUEST";
export const GET_INTEREST_SUCCESS = "GET_INTEREST_SUCCESS";
export const GET_INTEREST_FAIL = "GET_INTEREST_FAIL";

export const GET_SHIPMENT_BY_CRITERIA_REQUEST =
  "GET_SHIPMENT_BY_CRITERIA_REQUEST";
export const GET_SHIPMENT_BY_CRITERIA_SUCCESS =
  "GET_SHIPMENT_BY_CRITERIA_SUCCESS";
export const GET_SHIPMENT_BY_CRITERIA_FAIL = "GET_SHIPMENT_BY_CRITERIA_FAIL";

export const DELETE_SHIPMENT_REQUEST = "DELETE_SHIPMENT_REQUEST";
export const DELETE_SHIPMENT_SUCCESS = "DELETE_SHIPMENT_SUCCESS";
export const DELETE_SHIPMENT_FAIL = "DELETE_SHIPMENT_FAIL";

export const GET_INTERESTS_REQUEST = "GET_INTERESTS_REQUEST";
export const GET_INTERESTS_SUCCESS = "GET_INTERESTS_SUCCESS";
export const GET_INTERESTS_FAIL = "GET_INTERESTS_FAIL";

// TRACK

export const CREATE_TRACK_REQUEST = "CREATE_TRACK_REQUEST";
export const CREATE_TRACK_SUCCESS = "CREATE_TRACK_SUCCESS";
export const CREATE_TRACK_FAIL = "CREATE_TRACK_FAIL";

export const EDIT_TRACK_REQUEST = "EDIT_TRACK_REQUEST";
export const EDIT_TRACK_SUCCESS = "EDIT_TRACK_SUCCESS";
export const EDIT_TRACK_FAIL = "EDIT_TRACK_FAIL";

export const GET_TRACKS_REQUEST = "GET_TRACKS_REQUEST";
export const GET_TRACKS_SUCCESS = "GET_TRACKS_SUCCESS";
export const GET_TRACKS_FAIL = "GET_TRACKS_FAIL";

export const GET_TRACK_REQUEST = "GET_TRACK_REQUEST";
export const GET_TRACK_SUCCESS = "GET_TRACK_SUCCESS";
export const GET_TRACK_FAIL = "GET_TRACK_FAIL";

export const GET_TRACK_BY_CRITERIA_REQUEST = "GET_TRACK_BY_CRITERIA_REQUEST";
export const GET_TRACK_BY_CRITERIA_SUCCESS = "GET_TRACK_BY_CRITERIA_SUCCESS";
export const GET_TRACK_BY_CRITERIA_FAIL = "GET_TRACK_BY_CRITERIA_FAIL";

export const DELETE_TRACK_REQUEST = "DELETE_TRACK_REQUEST";
export const DELETE_TRACK_SUCCESS = "DELETE_TRACK_SUCCESS";
export const DELETE_TRACK_FAIL = "DELETE_TRACK_FAIL";

// TRIP

export const CREATE_TRIP_REQUEST = "CREATE_TRIP_REQUEST";
export const CREATE_TRIP_SUCCESS = "CREATE_TRIP_SUCCESS";
export const CREATE_TRIP_FAIL = "CREATE_TRIP_FAIL";

export const EDIT_TRIP_REQUEST = "EDIT_TRIP_REQUEST";
export const EDIT_TRIP_SUCCESS = "EDIT_TRIP_SUCCESS";
export const EDIT_TRIP_FAIL = "EDIT_TRIP_FAIL";

export const GET_TRIPS_REQUEST = "GET_TRIPS_REQUEST";
export const GET_TRIPS_SUCCESS = "GET_TRIPS_SUCCESS";
export const GET_TRIPS_FAIL = "GET_TRIPS_FAIL";

export const GET_TRIP_REQUEST = "GET_TRIP_REQUEST";
export const GET_TRIP_SUCCESS = "GET_TRIP_SUCCESS";
export const GET_TRIP_FAIL = "GET_TRIP_FAIL";

export const GET_TRIP_BY_CRITERIA_REQUEST = "GET_TRIP_BY_CRITERIA_REQUEST";
export const GET_TRIP_BY_CRITERIA_SUCCESS = "GET_TRIP_BY_CRITERIA_SUCCESS";
export const GET_TRIP_BY_CRITERIA_FAIL = "GET_TRIP_BY_CRITERIA_FAIL";

export const DELETE_TRIP_REQUEST = "DELETE_TRIP_REQUEST";
export const DELETE_TRIP_SUCCESS = "DELETE_TRIP_SUCCESS";
export const DELETE_TRIP_FAIL = "DELETE_TRIP_FAIL";

// ORDER

export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL";

export const EDIT_ORDER_REQUEST = "EDIT_ORDER_REQUEST";
export const EDIT_ORDER_SUCCESS = "EDIT_ORDER_SUCCESS";
export const EDIT_ORDER_FAIL = "EDIT_ORDER_FAIL";

export const GET_ORDERS_REQUEST = "GET_ORDERS_REQUEST";
export const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS";
export const GET_ORDERS_FAIL = "GET_ORDERS_FAIL";

export const GET_ORDER_BY_CRITERIA_REQUEST = "GET_ORDER_BY_CRITERIA_REQUEST";
export const GET_ORDER_BY_CRITERIA_SUCCESS = "GET_ORDER_BY_CRITERIA_SUCCESS";
export const GET_ORDER_BY_CRITERIA_FAIL = "GET_ORDER_BY_CRITERIA_FAIL";

export const DELETE_ORDER_REQUEST = "DELETE_ORDER_REQUEST";
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS";
export const DELETE_ORDER_FAIL = "DELETE_ORDER_FAIL";

//PAYMENT

export const CREATE_PAYMENT_REQUEST = "CREATE_PAYMENT_REQUEST";
export const CREATE_PAYMENT_SUCCESS = "CREATE_PAYMENT_SUCCESS";
export const CREATE_PAYMENT_FAIL = "CREATE_PAYMENT_FAIL";

export const EDIT_PAYMENT_REQUEST = "EDIT_PAYMENT_REQUEST";
export const EDIT_PAYMENT_SUCCESS = "EDIT_PAYMENT_SUCCESS";
export const EDIT_PAYMENT_FAIL = "EDIT_PAYMENT_FAIL";

export const GET_PAYMENTS_REQUEST = "GET_PAYMENTS_REQUEST";
export const GET_PAYMENTS_SUCCESS = "GET_PAYMENTS_SUCCESS";
export const GET_PAYMENTS_FAIL = "GET_PAYMENTS_FAIL";

export const GET_PAYMENT_BY_CRITERIA_REQUEST =
  "GET_PAYMENT_BY_CRITERIA_REQUEST";
export const GET_PAYMENT_BY_CRITERIA_SUCCESS =
  "GET_PAYMENT_BY_CRITERIA_SUCCESS";
export const GET_PAYMENT_BY_CRITERIA_FAIL = "GET_PAYMENT_BY_CRITERIA_FAIL";

export const DELETE_PAYMENT_REQUEST = "DELETE_PAYMENT_REQUEST";
export const DELETE_PAYMENT_SUCCESS = "DELETE_PAYMENT_SUCCESS";
export const DELETE_PAYMENT_FAIL = "DELETE_PAYMENT_FAIL";

// SUBSCRIPTION

export const CREATE_SUBSCRIBE_REQUEST = "CREATE_SUBSCRIBE_REQUEST";
export const CREATE_SUBSCRIBE_SUCCESS = "CREATE_SUBSCRIBE_SUCCESS";
export const CREATE_SUBSCRIBE_FAIL = "CREATE_SUBSCRIBE_FAIL";

export const EDIT_SUBSCRIBE_REQUEST = "EDIT_SUBSCRIBE_REQUEST";
export const EDIT_SUBSCRIBE_SUCCESS = "EDIT_SUBSCRIBE_SUCCESS";
export const EDIT_SUBSCRIBE_FAIL = "EDIT_SUBSCRIBE_FAIL";

export const GET_SUBSCRIBES_REQUEST = "GET_SUBSCRIBES_REQUEST";
export const GET_SUBSCRIBES_SUCCESS = "GET_SUBSCRIBES_SUCCESS";
export const GET_SUBSCRIBES_FAIL = "GET_SUBSCRIBES_FAIL";

export const GET_SUBSCRIPTION_BY_CRITERIA_REQUEST =
  "GET_SUBSCRIPTION_BY_CRITERIA_REQUEST";
export const GET_SUBSCRIPTION_BY_CRITERIA_SUCCESS =
  "GET_SUBSCRIPTION_BY_CRITERIA_SUCCESS";
export const GET_SUBSCRIPTION_BY_CRITERIA_FAIL =
  "GET_SUBSCRIPTION_BY_CRITERIA_FAIL";

export const DELETE_SUBSCRIBE_REQUEST = "DELETE_SUBSCRIBE_REQUEST";
export const DELETE_SUBSCRIBE_SUCCESS = "DELETE_SUBSCRIBE_SUCCESS";
export const DELETE_SUBSCRIBE_FAIL = "DELETE_SUBSCRIBE_FAIL";

//ASSIGN DRIVER

export const CREATE_ASSIGN_DRIVER_REQUEST = "CREATE_ASSIGN_DRIVER_REQUEST";
export const CREATE_ASSIGN_DRIVER_SUCCESS = "CREATE_ASSIGN_DRIVER_SUCCESS";
export const CREATE_ASSIGN_DRIVER_FAIL = "CREATE_ASSIGN_DRIVER_FAIL";

export const EDIT_ASSIGN_DRIVER_REQUEST = "EDIT_ASSIGN_DRIVER_REQUEST";
export const EDIT_ASSIGN_DRIVER_SUCCESS = "EDIT_ASSIGN_DRIVER_SUCCESS";
export const EDIT_ASSIGN_DRIVER_FAIL = "EDIT_ASSIGN_DRIVER_FAIL";

export const GET_ASSIGN_DRIVERS_REQUEST = "GET_ASSIGN_DRIVERS_REQUEST";
export const GET_ASSIGN_DRIVERS_SUCCESS = "GET_ASSIGN_DRIVERS_SUCCESS";
export const GET_ASSIGN_DRIVERS_FAIL = "GET_ASSIGN_DRIVERS_FAIL";

export const GET_ASSIGN_DRIVER_BY_CRITERIA_REQUEST =
  "GET_ASSIGN_DRIVER_BY_CRITERIA_REQUEST";
export const GET_ASSIGN_DRIVER_BY_CRITERIA_SUCCESS =
  "GET_ASSIGN_DRIVER_BY_CRITERIA_SUCCESS";
export const GET_ASSIGN_DRIVER_BY_CRITERIA_FAIL =
  "GET_ASSIGN_DRIVER_BY_CRITERIA_FAIL";

export const DELETE_ASSIGN_DRIVER_REQUEST = "DELETE_ASSIGN_DRIVER_REQUEST";
export const DELETE_ASSIGN_DRIVER_SUCCESS = "DELETE_ASSIGN_DRIVER_SUCCESS";
export const DELETE_ASSIGN_DRIVER_FAIL = "DELETE_ASSIGN_DRIVER_FAIL";

//PROFILE

export const CREATE_PROFILE_REQUEST = "CREATE_PROFILE_REQUEST";
export const CREATE_PROFILE_SUCCESS = "CREATE_PROFILE_SUCCESS";
export const CREATE_PROFILE_FAIL = "CREATE_PROFILE_FAIL";

export const EDIT_PROFILE_REQUEST = "EDIT_PROFILE_REQUEST";
export const EDIT_PROFILE_SUCCESS = "EDIT_PROFILE_SUCCESS";
export const EDIT_PROFILE_FAIL = "EDIT_PROFILE_FAIL";

export const GET_PROFILES_REQUEST = "GET_PROFILES_REQUEST";
export const GET_PROFILES_SUCCESS = "GET_PROFILES_SUCCESS";
export const GET_PROFILES_FAIL = "GET_PROFILES_FAIL";

export const GET_PROFILE_BY_CRITERIA_REQUEST =
  "GET_PROFILE_BY_CRITERIA_REQUEST";
export const GET_PROFILE_BY_CRITERIA_SUCCESS =
  "GET_PROFILE_BY_CRITERIA_SUCCESS";
export const GET_PROFILE_BY_CRITERIA_FAIL = "GET_PROFILE_BY_CRITERIA_FAIL";

export const DELETE_PROFILE_REQUEST = "DELETE_PROFILE_REQUEST";
export const DELETE_PROFILE_SUCCESS = "DELETE_PROFILE_SUCCESS";
export const DELETE_PROFILE_FAIL = "DELETE_PROFILE_FAIL";

//USER SUBSCRIPTION

export const CREATE_USER_SUBSCRIPTION_REQUEST =
  "CREATE_USER_SUBSCRIPTION_REQUEST";
export const CREATE_USER_SUBSCRIPTION_SUCCESS =
  "CREATE_USER_SUBSCRIPTION_SUCCESS";
export const CREATE_USER_SUBSCRIPTION_FAIL = "CREATE_USER_SUBSCRIPTION_FAIL";

export const EDIT_USER_SUBSCRIPTION_REQUEST = "EDIT_USER_SUBSCRIPTION_REQUEST";
export const EDIT_USER_SUBSCRIPTION_SUCCESS = "EDIT_USER_SUBSCRIPTION_SUCCESS";
export const EDIT_USER_SUBSCRIPTION_FAIL = "EDIT_USER_SUBSCRIPTION_FAIL";

export const GET_USER_SUBSCRIPTIONS_REQUEST = "GET_USER_SUBSCRIPTIONS_REQUEST";
export const GET_USER_SUBSCRIPTIONS_SUCCESS = "GET_USER_SUBSCRIPTIONS_SUCCESS";
export const GET_USER_SUBSCRIPTIONS_FAIL = "GET_USER_SUBSCRIPTIONS_FAIL";

export const GET_USER_SUBSCRIPTION_BY_CRITERIA_REQUEST =
  "GET_USER_SUBSCRIPTION_BY_CRITERIA_REQUEST";
export const GET_USER_SUBSCRIPTION_BY_CRITERIA_SUCCESS =
  "GET_USER_SUBSCRIPTION_BY_CRITERIA_SUCCESS";
export const GET_USER_SUBSCRIPTION_BY_CRITERIA_FAIL =
  "GET_USER_SUBSCRIPTION_BY_CRITERIA_FAIL";

export const DELETE_USER_SUBSCRIPTION_REQUEST =
  "DELETE_USER_SUBSCRIPTION_REQUEST";
export const DELETE_USER_SUBSCRIPTION_SUCCESS =
  "DELETE_USER_SUBSCRIPTION_SUCCESS";
export const DELETE_USER_SUBSCRIPTION_FAIL = "DELETE_USER_SUBSCRIPTION_FAIL";

export const UPGRADE_USER_SUBSCRIPTION_REQUEST =
  "UPGRADE_USER_SUBSCRIPTION_REQUEST";
export const UPGRADE_USER_SUBSCRIPTION_SUCCESS =
  "UPGRADE_USER_SUBSCRIPTION_SUCCESS";
export const UPGRADE_USER_SUBSCRIPTION_FAIL = "UPGRADE_USER_SUBSCRIPTION_FAIL";

//User
export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAIL = "CREATE_USER_FAIL";

export const EDIT_USER_REQUEST = "EDIT_USER_REQUEST";
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";
export const EDIT_USER_FAIL = "EDIT_USER_FAIL";

export const GET_USERS_REQUEST = "GET_USERS_REQUEST";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAIL = "GET_USERS_FAIL";

export const GET_USER_REQUEST = "GET_USERS_REQUEST";
export const GET_USER_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USER_FAIL = "GET_USERS_FAIL";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";

//COMPANY
export const CREATE_COMPANY_REQUEST = "CREATE_COMPANY_REQUEST";
export const CREATE_COMPANY_SUCCESS = "CREATE_COMPANY_SUCCESS";
export const CREATE_COMPANY_FAIL = "CREATE_COMPANY_FAIL";

export const EDIT_COMPANY_REQUEST = "EDIT_COMPANY_REQUEST";
export const EDIT_COMPANY_SUCCESS = "EDIT_COMPANY_SUCCESS";
export const EDIT_COMPANY_FAIL = "EDIT_COMPANY_FAIL";

export const GET_COMPANYS_REQUEST = "GET_COMPANYS_REQUEST";
export const GET_COMPANYS_SUCCESS = "GET_COMPANYS_SUCCESS";
export const GET_COMPANYS_FAIL = "GET_COMPANYS_FAIL";

export const GET_COMPANY_REQUEST = "GET_COMPANY_REQUEST";
export const GET_COMPANY_SUCCESS = "GET_COMPANY_SUCCESS";
export const GET_COMPANY_FAIL = "GET_COMPANY_FAIL";

export const DELETE_COMPANY_REQUEST = "DELETE_COMPANY_REQUEST";
export const DELETE_COMPANY_SUCCESS = "DELETE_COMPANY_SUCCESS";
export const DELETE_COMPANY_FAIL = "DELETE_COMPANY_FAIL";

//POP UP

export const POP_UP_SHOW = "POP_UP_SHOW";
export const POP_UP_CLOSE = "POP_UP_CLOSE";
